[module]
  [module.hugoVersion]
    extended = true
    min = "0.161.1"
## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------
#title = "ICClean"

## -----------------------------------------------
## Publish
## -----------------------------------------------
relativeURLs = true
# Local
baseURL = "/"
publishDir = "public"
# Production
# baseURL = "https://vsbsir.github.io/icclean/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------
disableKinds = ["taxonomy", "section"]

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------
[Params]
  tagline = "No Diplomas. No Jargon. Just a Clean Home."
  location = "Richmond Hill, Newmarket and surrounding GTA areas."
  companyName = "IC Clean"

[Params.asset]

[Params.social]
  email = "info@icclean.ca"
